FROM ubuntu:22.04
LABEL version="1.0"
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/ShangHai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY apt-ali-sources-2204.list /etc/apt/sources.list 
RUN apt update

RUN apt install -y cgdb curl gzip jq libaio1 libcurl4   libibverbs1 libicu-dev libjsoncpp25 librdmacm1 readline-common libstdc++6 libtool libuuid1 tar unzip  util-linux vim wget  net-tools 

#To install mariadb-server
RUN apt install -y mariadb-server

#To install java for zk and jconductor
RUN  apt install -y default-jre
